services:
  nginx:
    image: nginx:latest
    container_name: wp-nginx
    ports:
      - "8000:8000"     # for HTTP on port 8000
      - "443:443"       # required for HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
      - ./certs:/etc/ssl/certs
    depends_on:
      - wordpress
    networks:
      - wpsite
